### ISSUE TITLE
use multiple docker stages for auto-export

### ISSUE THREAD

**Issue by mars3142** [GodotNuts/GodotServer-Docker#3]
It would be more useful for the auto-export script, if the final container only contains the server binary and the pck file. A container with the complete source code if too much overhead.

**Comment by BearDooks** [comment]
@mars3142 I don't know how I missed this. That is a good point. For the auto export I have it download the repo to build the PCK, I could have it remove the source code later. I will look into this.

Thanks

Chuck

**Comment by mars3142** [comment]
I found a real good template (https://github.com/poszu/godot-servers-k8s/blob/main/Dockerfile) and I optimized it to reduce the container size. Now my Godot server (with minimal code to check the container) is 52MB.

    ARG GODOT_VERSION=3.3.2
    ARG GODOT_PROJECT_NAME
    ARG GODOT_EXPORT_PRESET=Linux/X11
    ARG GLIBC_VERSION=2.33-r0

    FROM barichello/godot-ci:$GODOT_VERSION as build
    # Exports the Godot project into a .pck file
    # Exporting requires an `export_presents.cfg` file in the root directory of the project.
    ARG GODOT_EXPORT_PRESET

    WORKDIR /src
    COPY . .

    RUN mkdir export && godot -v --export-pack ${GODOT_EXPORT_PRESET} export/server.pck

    FROM ubuntu:focal as godot-server
    # Downloads the godot server binary

    RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates wget unzip

    WORKDIR /bin

    ARG GODOT_VERSION
    RUN wget -c https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_linux_server.64.zip -O - | funzip > godot-server && chmod u+x godot-server

    FROM alpine:3
    # The output docker image. Runs the godot server with the exported pck
    ARG GODOT_PROJECT_NAME
    ARG GLIBC_VERSION

    # Allow this to run Godot
    RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
        && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-$GLIBC_VERSION.apk \
        && apk add glibc-$GLIBC_VERSION.apk \
        && rm -rf /var/cache/apk/* 

    WORKDIR /app
    COPY --from=godot-server /bin/godot-server server
    COPY --from=build /src/export/server.pck server.pck

    RUN mkdir -p ~/.config/godot \
        && mkdir -p ~/.local/share/godot/app_userdata/${GODOT_PROJECT_NAME} # A workaround for https://github.com/godotengine/godot/issues/44873 to silence the error 

    ENTRYPOINT ["/app/server"]

You need to check what's working for you.

**Comment by BearDooks** [comment]
@mars3142 

I just updated the could and merged it into the main branch. You will see the biggest (but really small) changes in the dockerfile where I changed the last part to this

`# Make needed directories for container
RUN mkdir /godotapp
RUN mkdir /godotbuildspace

# Move to the build space and export the .pck
WORKDIR /godotbuildspace
RUN git clone ${HTTPS_GIT_REPO} .
RUN godot --path /godotbuildspace --export-pack ${GODOT_EXPORT_PRESET} ${GODOT_GAME_NAME}.pck
RUN mv ${GODOT_GAME_NAME}.pck /godotapp/

# Change to the godotapp space, delete the source,  and run the app
WORKDIR /godotapp
run rm -f -R /godotbuildspace
CMD godot --main-pack ${GODOT_GAME_NAME}.pck`

I tested in my home lab and everything seems to be working fine.

Thanks for the suggestion!

Chuck
